/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.File;

public class App {

    public static void main(String[] args) {


        Bitmap newBitmap = new Bitmap();

        newBitmap.readBitmap(new File(args[0]));

        newBitmap.imageToFile(new File(args[1]));
    }
}
