/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.File;

public class App {

    public static void main(String[] args) {


        Bitmap newBitmap = new Bitmap();

        newBitmap.readBitmap(new File("src/main/assets/mario.bmp"));

        newBitmap.imageToFile(new File("src/main/assets/mario2.bmp"));
    }
}
